<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title><?php echo htmlspecialchars($page_title); ?></title>
<meta name="og:title" content="<?php echo htmlspecialchars($page_title); ?>"/>
<meta name="description" content="Fast and lightweight entity model framework for PHP without the fuss of an ORM."/>
<meta name="og:site_name" content="Contain PHP Entity Models"/>
<meta name="og:type" content="website"/>
<meta name="og:url" content="http://www.contain-php.org/"/>
<meta name="og:image" content="http://www.contain-php.org/images/logo.png"/>
<meta name="og:description" content="Fast and lightweight entity model framework for PHP without the fuss of an ORM."/>
<link rel="stylesheet" href="/css/style.css" media="screen" type="text/css"/>
<link rel="icon" href="/images/favicon.ico" type="image/x-icon" />
<link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon" />
<script src="/js/script.min.js" type="text/javascript"></script>
</head>
<body>
<?php echo $yield; ?>
</body>
</html>
