<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title><?php echo htmlspecialchars($page_title); ?></title>
<meta name="og:title" content="<?php echo htmlspecialchars($page_title); ?>">
<meta name="description" content="Fast and lightweight entity model framework for PHP without the fuss of an ORM.">
<meta name="og:site_name" content="Contain PHP Entity Models">
<meta name="og:type" content="website">
<meta name="og:url" content="http://www.contain-php.org/">
<meta name="og:image" content="http://www.contain-php.org/images/logo.png"/>
<meta name="og:description" content="Fast and lightweight entity model framework for PHP without the fuss of an ORM.">
<link rel="stylesheet" href="/css/style.css">
<link rel="icon" href="/images/favicon.ico" type="image/x-icon">
<link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon">
<link href='http://fonts.googleapis.com/css?family=Signika:600' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Noto+Sans' rel='stylesheet' type='text/css'>
<script src="/js/script.min.js" type="text/javascript"></script>
</head>
<body>
<header class="navbar navbar-static-top" id="top" role="banner">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="<?php echo $app->urlFor('home'); ?>" class="navbar-brand">Contain</a>
        </div>
        <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
            <ul class="nav navbar-nav">
                <li class="<?php if ($app->router()->getCurrentRoute()->getName() == 'documentation-page' && $app->router()->getCurrentRoute()->getParam('page') == 'getting-started'): echo 'active'; endif; ?>">
                    <a href="<?php echo $app->urlFor('documentation-page', array('page' => 'getting-started')); ?>">Getting Started</a>
                </li>
                <li class="<?php if ($app->router()->getCurrentRoute()->getName() == 'documentation'): echo 'active'; endif; ?>">
                    <a href="<?php echo $app->urlFor('documentation'); ?>">Documentation</a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="https://github.com/andrew-kandels/contain/issues?state=open">Issues</a></li>
            </ul>
        </nav>
    </div>
</header>
<div class="container page-container" role="main">
<?php 
if ($markdown) {
    $html = \Michelf\MarkdownExtra::defaultTransform($yield);
    echo \Michelf\SmartyPants::defaultTransform($html);
} else {
    echo $yield; 
}
?>
</div>
<footer class="footer">
    <div class="container">
        Contain is released under the BSD-2 license. You may use it freely with or without attribution.
    </div>
</footer>
</body>
</html>
